/* Site-specific Maxima code can be put here */

load("inv_trig_tex.lisp");

load("diff.mac");
load("finmap.mac");
load("functions.mac");
load("mcq.mac");
load("one_d_critical.mac");
load("two_d_critical.mac");
load("partial_fractions.mac");
load("svg.mac");
load("extra_inequalities.mac");
load("vectors");
load("linalg.mac");
load("stack_misc.mac");
load("int.mac");
load("double_int.mac");
load("permutations.mac");
load("groups.mac");
load("builder.mac");
load("comb.mac");